name: test-secret-vars
on: 
  workflow_dispatch:
jobs:
  build-with-secrets:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Use secrets
      run: |
        token=${{ secrets.TEST_SECRET }}
        echo ${token:1}
        echo "repo variable : ${{ vars.TEST_REPO_VAR }}"
